# Generated by Django 5.1 on 2024-09-05 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_carts', to='product.product')),
                ('user_of_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart_with_this_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
