# Generated by Django 5.1 on 2024-09-30 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='user_of_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Cart_with_this_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_inThisCart', to='Cart.cartmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='addtocart',
            unique_together={('cart_product', 'cart')},
        ),
    ]
