# Generated by Django 5.1 on 2024-09-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
