# Generated by Django 5.1 on 2024-09-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_cartmodel_cart_product'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_carts', to='product.product', unique=True),
        ),
    ]
