# Generated by Django 5.1 on 2024-09-05 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_cartmodel_cart_product'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='cart_product',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='user_of_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Cart_with_this_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='addToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_inThisCart', to='Cart.cartmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_product', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'cart')},
            },
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cart_product',
            field=models.ManyToManyField(through='Cart.addToCart', to='product.product'),
        ),
    ]
