# Generated by Django 5.1 on 2024-09-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_remove_cartmodel_product_quantity_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='product',
            new_name='cart_product',
        ),
        migrations.AlterUniqueTogether(
            name='addtocart',
            unique_together={('cart_product', 'cart')},
        ),
    ]
