# Generated by Django 5.1 on 2024-09-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_rename_product_addtocart_cart_product_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_product',
            field=models.ManyToManyField(through='Cart.AddToCart', to='product.product'),
        ),
    ]
