# Generated by Django 5.1 on 2024-09-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
