# Generated by Django 5.1 on 2024-09-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='address',
            field=models.CharField(default='Lahore', max_length=100),
        ),
    ]
