# Generated by Django 5.1 on 2024-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_webuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webuser',
            name='address',
        ),
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.CharField(default='Lahore', max_length=100),
        ),
    ]
