# Generated by Django 5.1 on 2024-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_remove_webuser_address_alter_webuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='address',
            field=models.CharField(default='Lahore', max_length=100),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
