# Generated by Django 5.1 on 2024-09-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bill', models.FloatField(blank=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('checkout_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checking_out_order_detail', to='checkout.checkoutpage')),
                ('user_ordering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
