# Generated by Django 5.1 on 2024-09-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checking_out_order_detail', to='checkout.checkoutpage'),
        ),
    ]
