# Generated by Django 5.1 on 2024-09-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_checkout_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_ordering',
            new_name='ordered_by_user',
        ),
    ]
